const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  onStatus: (cb) => ipcRenderer.on('status', (_e, s) => cb(s)),
  confirmDshPath: (p) => ipcRenderer.invoke('confirm-dsh-path', p),
  browseDshPath: () => ipcRenderer.invoke('browse-dsh-path'),
  retry: () => ipcRenderer.invoke('retry'),
  restartDsh: () => ipcRenderer.invoke('restart-dsh'),
  openMenu: (menuId, rect) => ipcRenderer.invoke('open-menu', menuId, rect),
  onDropdownPopup: (cb) => ipcRenderer.on('dropdown-popup', (_e, menuId, p) => cb(menuId, p)),
  dropdownAction: (menuId, action) => ipcRenderer.send('dropdown-action', menuId, action),
  dropdownClosed: (menuId) => ipcRenderer.send('dropdown-closed', menuId),
  onDropdownMenuState: (cb) => ipcRenderer.on('dropdown-menu-state', (_e, menuId, open) => cb(menuId, open)),
  openRepo: () => ipcRenderer.invoke('open-repo'),
  openLog: () => ipcRenderer.invoke('open-log'),
  getAppInfo: () => ipcRenderer.invoke('get-app-info'),
  checkDshUpdate: () => ipcRenderer.invoke('check-dsh-update'),
  onChromeTheme: (cb) => ipcRenderer.on('chrome-theme', (_e, d) => cb(d)),
  onChromeLanguage: (cb) => ipcRenderer.on('chrome-language', (_e, l) => cb(l)),
  onChromeBtnsState: (cb) => ipcRenderer.on('chrome-btns-state', (_e, visible) => cb(visible)),
  onChromeBarVisible: (cb) => ipcRenderer.on('chrome-bar-visible', (_e, visible) => cb(visible)),
  onFullscreenMode: (cb) => ipcRenderer.on('chrome-fullscreen', (_e, on) => cb(on)),
  notifyTaskComplete: () => ipcRenderer.send('task-complete'),
  // 文件树面板
  onFilePanelState: (cb) => ipcRenderer.on('file-panel-state', (_e, open) => cb(open)),
  toggleFilesPanel: () => ipcRenderer.invoke('toggle-file-panel'),
  readDirectory: (dirPath) => ipcRenderer.invoke('read-directory', dirPath),
  readFile: (filePath) => ipcRenderer.invoke('read-file', filePath),
  writeFile: (filePath, content) => ipcRenderer.invoke('write-file', filePath, content),
  getWorkspaceRoot: () => ipcRenderer.invoke('get-workspace-root'),
});
